"""
script_utils.py — Shared script helpers extracted from server.py.

Both server.py and tool_handlers.py import from this module.
All functions are self-contained (no imports from server.py).
"""

import re
import textwrap


# ---------------------------------------------------------------------------
# Code cleaning / wrapping helpers
# ---------------------------------------------------------------------------

def _sanitize_step_label(raw_label, max_len=72):
    label = (raw_label or "").strip()
    label = label.replace("\\", "/").replace('"', "'")
    label = re.sub(r"\s+", " ", label)
    if len(label) > max_len:
        return label[: max_len - 3].rstrip() + "..."
    return label


def clean_generated_code(code: str) -> str:
    """Strip markdown fences, fix common bad patterns, remove wrapper boilerplate."""
    from fusion_api_knowledge import apply_api_repairs

    # Remove markdown code fences
    raw = re.sub(r"```[^\n]*\n", "", code)
    raw = re.sub(r"```", "", raw)
    # Repair common invalid selection access generated by the model.
    raw = re.sub(r"\bapp\s*\.\s*activeSelections\b", "ui.activeSelections", raw)
    raw = re.sub(r"adsk\.core\.Application\.get\(\)\s*\.\s*activeSelections", "ui.activeSelections", raw)
    raw = re.sub(
        r"targetFace\s*=\s*ui\.activeSelections\.item\(0\)\.entity",
        "targetFace = adsk.fusion.BRepFace.cast(ui.activeSelections.item(0).entity)",
        raw,
    )
    # Repair common wrong combine target body choice when a face selection is used.
    raw = re.sub(
        r"combineFeats\.createInput\(\s*rootComp\.bRepBodies\.item\(0\)\s*,\s*toolBodies\s*\)",
        "combineFeats.createInput(targetFace.body, toolBodies)",
        raw,
    )
    raw = re.sub(
        r"combineFeats\.createInput\(\s*root\.bRepBodies\.item\(0\)\s*,\s*toolBodies\s*\)",
        "combineFeats.createInput(targetFace.body, toolBodies)",
        raw,
    )
    raw = apply_api_repairs(raw)

    lines = raw.splitlines()
    cleaned = []
    skip_next_empty = False

    for line in lines:
        l = line.strip().lower()

        # Skip friendly text/boilerplate
        if l.startswith(("sure", "here is", "here's", "this script", "note:", "you can use")):
            skip_next_empty = True
            continue

        # Skip nested run() definitions (wrapper adds this)
        if "def run(" in l:
            skip_next_empty = True
            continue

        # Skip adsk imports (wrapper adds this)
        if l.startswith("import") and "adsk" in l:
            skip_next_empty = True
            continue

        # Skip setup code (wrapper adds this)
        if l in ["design = app.activeproduct", "rootcomp = design.rootcomponent", "sketches = rootcomp.sketches"]:
            skip_next_empty = True
            continue

        # Skip empty lines after removed content
        if not l and skip_next_empty:
            skip_next_empty = False
            continue

        cleaned.append(line)

    return "\n".join(cleaned)


def _normalize_indentation(code: str, indent: int = 8) -> str:
    dedented = textwrap.dedent(code).strip()
    return "\n".join(" " * indent + line if line else "" for line in dedented.splitlines())


def wrap_script_with_run(code: str, clear_model: bool = False) -> str:
    """Wrap a code body in the standard Fusion 360 run() function skeleton."""
    cleanup_block = '''
design = app.activeProduct
root = design.rootComponent
features_to_delete = []
for i in range(root.features.count):
    features_to_delete.append(root.features.item(i))
for feat in features_to_delete:
    try:
        feat.deleteMe()
    except:
        pass
sketches_to_delete = []
for i in range(root.sketches.count):
    sketches_to_delete.append(root.sketches.item(i))
for sketch in sketches_to_delete:
    try:
        sketch.deleteMe()
    except:
        pass
bodies_to_delete = []
for i in range(root.bRepBodies.count):
    bodies_to_delete.append(root.bRepBodies.item(i))
for body in bodies_to_delete:
    try:
        body.deleteMe()
    except:
        pass
'''

    # Always include setup code to ensure variables are defined
    setup_block = '''
design = app.activeProduct
rootComp = design.rootComponent
sketches = rootComp.sketches
'''

    return (
        "import adsk.core, adsk.fusion, traceback\n\n"
        "def run(context):\n"
        "    app = adsk.core.Application.get()\n"
        "    ui = app.userInterface\n"
        "    _mcp_ctx = {'step': 'initializing'}\n"
        "    def checkpoint(step_name):\n"
        "        _mcp_ctx['step'] = str(step_name)\n"
        "    try:\n"
        "        checkpoint('setup')\n"
        + (_normalize_indentation(cleanup_block, indent=8) + "\n\n" if clear_model else "")
        + _normalize_indentation(setup_block, indent=8) + "\n\n"
        + _normalize_indentation(code, indent=8)
        + "\n"
        "    except Exception as e:\n"
        "        failed_step = _mcp_ctx.get('step', 'unknown')\n"
        "        enriched_error = '[STEP:{}] {}'.format(failed_step, str(e))\n"
        "        if ui and 'SELECTION_REQUIRED' not in str(e):\n"
        "            ui.messageBox('❌ Runtime Error: {}'.format(enriched_error))\n"
        "        raise RuntimeError(enriched_error) from e\n"
    )


def add_execution_checkpoints(code: str, user_prompt: str = "") -> str:
    """Insert checkpoint() calls before each major operation in the code body."""
    lines = code.splitlines()
    base_label = "begin generated script"
    if not any(line.strip() for line in lines):
        base_label = _sanitize_step_label(user_prompt) or "generated operation"
    out = [f'checkpoint("step_0: {base_label}")']
    step_count = 0

    for line in lines:
        stripped = line.strip()

        if line.startswith("#"):
            label = _sanitize_step_label(stripped.lstrip("#").strip())
            if label:
                step_count += 1
                out.append(f'checkpoint("step_{step_count}: {label}")')

        # Add checkpoints for top-level feature adds when comments are absent.
        if not line.startswith((" ", "\t")):
            m_add = re.search(r"\b(\w+)\.add\(", line)
            if m_add and "checkpoint(" not in line:
                step_count += 1
                out.append(f'checkpoint("step_{step_count}: {m_add.group(1)}.add feature")')

        out.append(line)

    return "\n".join(out)


# ---------------------------------------------------------------------------
# State summarisation helpers
# ---------------------------------------------------------------------------

def summarize_fusion_state(state: dict) -> str:
    """Return a human-readable summary of the Fusion 360 model state dict."""
    if not state:
        return "No state snapshot available."
    lines = []
    timestamp = state.get("timestamp", "unknown")
    units = state.get("units", "cm")
    lines.append(f"Last updated: {timestamp}")
    lines.append(
        f"Bodies: {state.get('body_count', 0)}, "
        f"Sketches: {state.get('sketch_count', 0)}, "
        f"Features: {state.get('feature_count', 0)}, "
        f"Units: {units}"
    )
    for body in state.get("bodies", []):
        name = body.get("name", "Body")
        bbox = body.get("bbox") or {}
        size_dict = bbox.get("size") or {}
        center_dict = bbox.get("center") or {}
        size = body.get("size_cm") or [
            size_dict.get("x", 0),
            size_dict.get("y", 0),
            size_dict.get("z", 0),
        ]
        center = body.get("center_cm") or [
            center_dict.get("x", 0),
            center_dict.get("y", 0),
            center_dict.get("z", 0),
        ]
        faces = body.get("face_count", 0)
        lines.append(
            f"- {name}: size {size[0]:.2f}x{size[1]:.2f}x{size[2]:.2f} cm, "
            f"center {center[0]:.2f},{center[1]:.2f},{center[2]:.2f} cm, "
            f"faces {faces}"
        )

    # Include origin construction planes so LLM knows they're available
    origin_planes = state.get("origin_planes", [])
    if origin_planes:
        lines.append("Origin planes:")
        for p in origin_planes:
            lines.append(f"  - {p['name']} → {p['code']} ({p['label']})")

    return "\n".join(lines)


def summarize_selection_context(selection: dict) -> str:
    """Return a human-readable summary of the active selection context dict."""
    if not selection:
        return "No active selections."

    if isinstance(selection, list):
        items = selection
        count = len(items)
    else:
        items = selection.get("items", []) if isinstance(selection, dict) else []
        count = selection.get("count", len(items)) if isinstance(selection, dict) else len(items)

    if count == 0:
        return "No active selections."

    lines = [f"Active selections: {count}"]
    for item in items[:8]:
        kind = item.get("kind", item.get("object_type", "unknown"))
        index = item.get("index", 0)
        if kind == "face":
            normal = item.get("normal") or [0, 0, 0]
            body_name = item.get("body_name", "body")
            area = item.get("area_cm2", 0)
            lines.append(
                f"- [{index}] face on {body_name}, normal {normal[0]:.3f},{normal[1]:.3f},{normal[2]:.3f}, area {area:.2f} cm^2"
            )
        elif kind == "body":
            lines.append(
                f"- [{index}] body {item.get('name', 'Body')}, volume {item.get('volume_cm3', 0):.2f} cm^3"
            )
        elif kind == "edge":
            lines.append(f"- [{index}] edge length {item.get('length_cm', 0):.2f} cm")
        elif kind == "vertex":
            point = item.get("point") or {}
            lines.append(
                f"- [{index}] vertex at {point.get('x', 0):.2f},{point.get('y', 0):.2f},{point.get('z', 0):.2f}"
            )
        elif kind == "constructionplane":
            plane_name = item.get("plane_name") or item.get("name", "unknown plane")
            lines.append(
                f"- [{index}] construction plane '{plane_name}' "
                f"(use: sketches.add(entity) where entity = ui.activeSelections.item({index}).entity)"
            )
        elif kind == "constructionaxis":
            axis_name = item.get("axis_name") or item.get("name", "unknown axis")
            lines.append(f"- [{index}] construction axis '{axis_name}'")
        else:
            lines.append(f"- [{index}] {kind}")

    if count > 8:
        lines.append(f"... {count - 8} more selections")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Heuristic: should we wipe the model before applying this operation?
# ---------------------------------------------------------------------------

def should_clear_model(prompt: str, fusion_state: dict) -> bool:
    """Return True if the prompt implies the user wants to start from scratch."""
    p = prompt.lower()
    explicit_reset = [
        "reset",
        "start over",
        "start new",
        "new design",
        "clear design",
        "from scratch",
        "delete everything",
    ]
    if any(phrase in p for phrase in explicit_reset):
        return True

    has_geometry = False
    if isinstance(fusion_state, dict):
        has_geometry = fusion_state.get("body_count", 0) > 0

    # model_summary is not available here; fall back to geometry presence only
    if not has_geometry:
        seed_words = [
            "create",
            "make",
            "build",
            "new",
            "cube",
            "box",
            "cylinder",
            "sphere",
        ]
        return any(word in p for word in seed_words)
    return False
